name: Update Profile Views
on:
  schedule:
    - cron: "0 */6 * * *" # Runs every 6 hours
  workflow_dispatch:
jobs:
  update-counter:
    runs-on: ubuntu-latest
    steps:
      - uses: gayanvoice/github-profile-views-counter@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
